# Note to self: 
# I can't get version 3.8 for the server without updating the OS.
# On the server, you have to run
#           build: `sudo $DOCKER_CONFIG/cli-plugins/docker-compose build`
#             and: `sudo $DOCKER_CONFIG/cli-plugins/docker-compose up -d`
#    to view logs: `sudo $DOCKER_CONFIG/cli-plugins/docker-compose logs`
version: "3.8"
services:
  api:
    build:
      context: ./transperler-service
      dockerfile: Dockerfile
    image: transpiler-service:latest
    ports:
      - 3456:3456
